//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class challenge_settings
    {
        public Nullable<int> ChallengeID { get; set; }
        public string SettingName { get; set; }
        public string SettingValue { get; set; }
        public int ChallengeSettingsID { get; set; }
    
        public virtual challenge challenge { get; set; }
    }
}
