//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class challenges_and_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public challenges_and_users()
        {
            this.challenges_and_posts = new HashSet<challenges_and_posts>();
        }
    
        public int ChallengesAndUsersID { get; set; }
        public string ChallengeStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ChallengeID { get; set; }
    
        public virtual challenge challenge { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<challenges_and_posts> challenges_and_posts { get; set; }
    }
}
