//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public challenge()
        {
            this.challenge_settings = new HashSet<challenge_settings>();
            this.challenges_and_users = new HashSet<challenges_and_users>();
            this.notifications = new HashSet<notification>();
            this.posts = new HashSet<post>();
        }
    
        public int ChallengeID { get; set; }
        public string ChallengeType { get; set; }
        public string ChallengeName { get; set; }
        public string ChallengeHashTag { get; set; }
        public string ChallengeStatus { get; set; }
        public Nullable<System.DateTime> ChallengeCreateDate { get; set; }
        public Nullable<int> ChallengeCreateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<challenge_settings> challenge_settings { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<challenges_and_users> challenges_and_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> posts { get; set; }
    }
}
