//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class challenges_and_users
    {
        public int ChallengesAndUsersID { get; set; }
        public string ChallengeStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ChallengeID { get; set; }
    
        public virtual challenge challenge { get; set; }
        public virtual user user { get; set; }
    }
}
