//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class challenges_and_posts
    {
        public Nullable<int> ChallengesAndUsersID { get; set; }
        public Nullable<int> PostID { get; set; }
        public int ChallengesAndPostsID { get; set; }
    
        public virtual challenges_and_users challenges_and_users { get; set; }
        public virtual post post { get; set; }
    }
}
