//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_users
    {
        public string NotificationState { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int NotificationUsersID { get; set; }
    
        public virtual notification notification { get; set; }
        public virtual user user { get; set; }
    }
}
