//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_comments
    {
        public int PostCommentID { get; set; }
        public string PostCommentDiscription { get; set; }
        public Nullable<int> PostCommentLike { get; set; }
        public Nullable<System.DateTime> PostCommentCreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PostID { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
