//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.notifications = new HashSet<notification>();
            this.post_comments = new HashSet<post_comments>();
            this.challenges_and_posts = new HashSet<challenges_and_posts>();
        }
    
        public int PostID { get; set; }
        public string PostContent { get; set; }
        public string PostDiscription { get; set; }
        public Nullable<int> PostLikes { get; set; }
        public Nullable<System.DateTime> PostCreateDate { get; set; }
        public Nullable<int> ChallengeID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual challenge challenge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_comments> post_comments { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<challenges_and_posts> challenges_and_posts { get; set; }
    }
}
