//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeMeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_followers
    {
        public int UserID { get; set; }
        public Nullable<int> UserFollowerID { get; set; }
        public int UsersFollowersID { get; set; }
    
        public virtual user user { get; set; }
    }
}
